---
## aliBuild configuration template (default values used if absent) ##
# aliBuild: # optional
#   dir_alice: "$HOME/alice" # build directory with repositories of aliBuild packages
#   architecture: "" # system architecture, automatically determined by aliBuild if empty or absent
#   options: "" # aliBuild command line options
#   clean: 1 # Run aliBuild clean at the end.
#   clean_aggressive: 0 # Use the '--aggressive-cleanup' option.
#   clean_purge: 0 # Keep only the latest builds and delete the rest.

repositories:

  ## package configuration template (default values used if absent) ##
  # name:
  #   path: "dir_alice/name" # path to the Git repository
  #   update: 1 # Update the Git repository.
  #   upstream: "upstream" # name of the upstream remote (central repo)
  #   origin: "" # name of the origin remote (fork repo), usually "origin", ignored if empty or absent
  #   branch: "master" # name of the main branch
  #   build: 0 # Build the package with aliBuild. Absent by default. If present, package is considered in the cleanup.
  #   build_opt: "--defaults o2" # aliBuild command line options, absent by default

  alidist:
    update: 1

  AliPhysics:
    update: 1
    build: 1
    origin: "origin"

  O2:
    update: 1
    build: 1
    origin: "origin"
    branch: "dev"

  O2Physics:
    update: 1
    build: 1
    origin: "origin"

  Run3Analysisvalidation:
    update: 1
