---
## aliBuild configuration template (default values used if absent) ##
aliBuild: # optional
#   dir_alice: "$HOME/alice" # build directory with repositories of aliBuild packages
  architecture: "ubuntu2404_x86-64" # system architecture, automatically determined by aliBuild if empty or absent
#   options: "" # aliBuild command line options
  clean: 0 # Run aliBuild clean at the end.
  clean_aggressive: 1 # Use the '--aggressive-cleanup' option.
  clean_purge: 1 # Keep only the latest builds and delete the rest.

repositories:

  ## package configuration template (default values used if absent) ##
  # name:
  #   path: "dir_alice/name" # path to the Git repository
  #   update: 1 # Update the Git repository.
  #   upstream: "upstream" # name of the upstream remote (central repo)
  #   origin: "" # name of the origin remote (fork repo), usually "origin", ignored if empty or absent
  #   branch: "master" # name of the main branch
  #   build: 0 # Build the package with aliBuild. Absent by default. If present, package is considered in the cleanup.
  #   build_opt: "--defaults o2" # aliBuild command line options, absent by default

  alice-analysis-tutorial:
    update: 1

  ali-bot:
    update: 1

  alibuild:
    update: 1

  alibuild-recipe-tools:
    update: 1

  alidist:
    update: 1

  alidistlint:
    update: 1

  alisw-github-io:
    update: 1

  analysis-framework:
    update: 1

  analysis-tutorials:
    update: 1

  ci-jobs:
    update: 1

  CodingGuidelines:
    update: 1

  docks:
    update: 1

  homebrew-system-deps:
    update: 1

  O2:
    update: 1
    branch: dev

  O2-wiki:
    update: 1

  O2Physics:
    update: 1

  O2Physics-wiki:
    update: 1

  Run3AnalysisValidation:
    update: 1
