Xi_cc:
  pp14p0:
    absy1p44:
      latexcand: "#Xi_{cc}"
      inputBkg: /data/Run5/results/20200602_9am_loosecuts/AnalysisResults_O2_MB.root
      inputSig: /data/Run5/results/20200602_9am_loosecuts/AnalysisResults_O2_enriched.root
      dirname: hf-task-xicc-mc
      normalized: 1
      varlist: ["mass", "d0Prong0", "d0Prong1", "CPA", "Y", "DecLength", "Ct", "Eta", "chi2PCA"]
      varlatex: ["inv. mass (GeV)", "d_{0} prong 0 (cm)", "d_{0} prong 1 (cm)", "cos(#theta_{p})", "rapidity", "dec. length (cm)", "c#tau (cm)", "#eta", "chi^{2} decay"]
      histonamesig: ["hMassSig", "hd0Prong0Sig", "hd0Prong1Sig", "hCPASig", "hYSig", "hDecLengthSig", "hCtSig", "hEtaSig", "hChi2PCASig"]
      histonamebkg: ["hMassBg", "hd0Prong0Bg", "hd0Prong1Bg", "hCPABg", "hYBg", "hDecLengthBg", "hCtBg", "hEtaBg", "hChi2PCABg"]
      ymin: [0.0001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
      ymax: [0.4, 5., 5., 5., 5., 5., 10., 5., 5.]
      xmin: [3.2, -0.01, -0.01, 0.5, -3., 0.00001, 0., -3., 0.]
      xmax: [4., 0.04, 0.04, 1.1, 3., 3., 0.1, 3., 0.1]
      rebin: [5, 2, 5, 2, 5, 5, 5, 5, 5]
      dolog: [0, 1, 1, 1, 1, 1, 1, 1, 1]
      dologx: [0, 1, 0, 0, 0, 1, 0, 0, 1]
      legtoleft: [1, 1, 1, 1, 1, 1, 1, 1, 1]

X3872:
  pp14p0:
    absy1p44:
      latexcand: "X(3872)"
      inputBkg: /data/Run5/results/Xanalysis_0p7pt_RICHTOF/AnalysisResults_O2_MB.root
      inputSig: /data/Run5/results/Xanalysis_0p7pt_RICHTOF/AnalysisResults_O2_enriched.root
      dirname: hf-task-x-mc
      normalized: 1
      varlist: ["mass", "d0Prong0", "d0Prong1", "CPA", "Y", "DecLength", "Ct", "Eta", "chi2PCA"]
      varlatex: ["inv. mass (GeV)", "d_{0} prong 0 (cm)", "d_{0} prong 1 (cm)", "cos(#theta_{p})", "rapidity", "dec. length (cm)", "c#tau (cm)", "#eta", "chi^{2} decay"]
      histonamesig: ["hMassRecSig", "hd0Prong0RecSig", "hd0Prong1RecSig", "hCPARecSig", "hYSig", "hDeclengthRecSig", "hCtSig", "hEtaRecSig", "hChi2PCASig"]
      histonamebkg: ["hMassRecBg", "hd0Prong0RecBg", "hd0Prong1RecBg", "hCPARecBg", "hYBg", "hDeclengthRecBg", "hCtBg", "hEtaRecBg", "hChi2PCABg"]
      ymin: [0.0001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
      ymax: [0.4, 5., 5., 5., 5., 5., 10., 5., 5.]
      xmin: [3.2, -0.01, -0.01, 0.5, -3., 0.00001, 0., -3., 1.e-6]
      xmax: [4., 0.04, 0.04, 1.1, 3., 3., 0.1, 3., 0.1]
      rebin: [5, 2, 5, 5, 5, 5, 5, 5, 5]
      dolog: [0, 1, 1, 1, 1, 1, 1, 1, 1]
      dologx: [0, 1, 0, 0, 0, 1, 0, 0, 1]
      legtoleft: [1, 1, 1, 1, 1, 1, 1, 1, 1]

Jpsi:
  pp14p0:
    absy1p44:
      latexcand: "Jpsi"
      inputBkg: /data/Run5/results/Xanalysis_0p7pt_RICHTOF/AnalysisResults_O2_MB.root
      inputSig: /data/Run5/results/Xanalysis_0p7pt_RICHTOF/AnalysisResults_O2_enriched.root
      dirname: hf-task-jpsi-mc
      normalized: 1
      varlist: ["mass", "d0Prong0", "d0Prong1", "Y", "DecLength", "Ct", "d0xd0", "chi2PCA"]
      varlatex: ["inv. mass (GeV)", "d_{0} prong 0 (cm)", "d_{0} prong 1 (cm)", "rapidity", "dec. length (cm)", "c#tau (cm)", "d_{0} x d_{1}", "chi^{2} decay"]
      histonamesig: ["hMassSig", "hd0Prong0Sig", "hd0Prong1Sig", "hYSig", "hDecLengthSig", "hCtSig", "hd0d0Sig", "hChi2PCASig"]
      histonamebkg: ["hMassBg", "hd0Prong0Bg", "hd0Prong1Bg", "hYBg", "hDecLengthBg", "hCtBg", "hd0d0Bg", "hChi2PCABg"]
      ymin: [0.0001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
      ymax: [0.4, 5., 5., 5., 5., 10., 5., 5.]
      xmin: [3.2, -0.01, -0.01, -3., 0.00001, 0., -0.02, 1.e-6]
      xmax: [4., 0.04, 0.04, 3., 3., 0.1, 0.02, 0.1]
      rebin: [5, 5, 5, 5, 1, 5, 5, 1]
      dolog: [0, 1, 1, 1, 1, 1, 1, 1]
      dologx: [0, 1, 0, 0, 1, 0, 0, 1]
      legtoleft: [1, 1, 1, 1, 1, 1, 1, 1]
